### ISSUE TITLE
"Some bytes were not transmitted" error message?

### ISSUE THREAD

**Issue by condector** [raleighlittles/PS5-Camera-Firmware-Loader#1]
Error when trying to inject the firmware:

```
[ 3.531716] [00001e8c] libusb: debug [libusb_alloc_transfer] transfer 0x55a3523cc440
[ 3.531719] [00001e8c] libusb: debug [libusb_submit_transfer] transfer 0x55a3523cc440
[ 3.531722] [00001e8c] libusb: debug [add_to_flying_list] arm timerfd for timeout in 1000ms (first in line)
[ 3.531728] [00001e8c] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 3.531731] [00001e8c] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[ 3.535178] [00001e8c] libusb: debug [handle_events] poll() returned 1
[ 3.535187] [00001e8c] libusb: debug [reap_for_handle] urb type=2 status=-71 transferred=0
[ 3.535213] [00001e8c] libusb: debug [handle_control_completion] handling completion status -71
[ 3.535216] [00001e8c] libusb: debug [handle_control_completion] low-level bus error occurred
[ 3.535220] [00001e8c] libusb: debug [disarm_timerfd] 
[ 3.535225] [00001e8c] libusb: debug [usbi_handle_transfer_completion] transfer 0x55a3523cc440 has callback 0x7f2c5f391fc0
[ 3.535229] [00001e8c] libusb: debug [sync_transfer_cb] actual_length=0
[ 3.535233] [00001e8c] libusb: debug [libusb_free_transfer] transfer 0x55a3523cc440
ERROR: Some bytes were not transmitted
```

I'm using Ubuntu 20.04 LTS, if that matters.

**Comment by raleighlittles** [comment]
I've noticed this "error" occasionally happens, but I'm not sure why. Also, at least in my testing, this doesn't seem to actually indicate any failure occurred. As long as you see the line:

> Found UVC 1.00 device USB Camera-OV580 (05a9:058c)

Then it worked correctly.

**Comment by raleighlittles** [comment]
I renamed your issue title and pinned it so that others can see it. I'd have to do more particular debugging to try to figure out why this sometimes occurs.

**Comment by condector** [comment]
> Found UVC 1.00 device USB Camera-OV580 (05a9:058c)

That was my problem. I saw the errors and the `dmesg` does not show this specific message. Then I start to investigate and track the error to "understand". I try the same strategy but with Windows and worked. So the camera is ok. But I only use Linux, so, I'm trying to figure out, "what's going on". Thanks for your answer.

**Comment by d2a-raudenaerde** [comment]
I have the same error as @condector, on ubuntu 21.10. I installend  libusb-1.0-0-dev and am running kernel 5.13.19

**Comment by raleighlittles** [comment]
@d2a-raudenaerde Did you have any other errors, as in -- was the UVC device still correctly identified despite this?

**Comment by raleighlittles** [comment]
If I can reliably show that the error for some reason doesn't affect operational usage of the camera, I'm inclined to just remove the error and change it to a warning message.

**Comment by d2a-raudenaerde** [comment]
@raleighlittles the first tries, no new UVC device. Then, I switched usb port and got less errors (only after the last transmission), and it worked. Maybe my usb port is too fast for the device?

**Comment by raleighlittles** [comment]
Good question. Using that as a lead, I tried adjusting the LIBUSB_SPEED parameter here: https://github.com/raleighlittles/PS5-Camera-Firmware-Loader/blob/master/main.cpp#L40 across [different values](https://vovkos.github.io/doxyrest/samples/libusb/enum_libusb_speed.html) but I didn't have any luck. Changing the libusb speed to anything other than unknown leads to libusb being unable to open the device.

**Comment by raleighlittles** [comment]
@d2a-raudenaerde Usually USB standards are supposed to be backwards compatible, so you can use an older device on a newer hub. It could be the other way around though. Since it seems to be working for you, I'm going to close this bug for now, but if you start to have issues again you can re-open it and we will discuss
