### ISSUE TITLE
libusb crate no longer supported

### ISSUE THREAD

**Issue by parkerlreed** [raleighlittles/PS5-Camera-Firmware-Loader#11]
### Provide a brief description of the issue

https://github.com/rust-lang/cargo/issues/9885

libusb is unmaintined and depends on bit-set 0.2.0 which no longer compiles

rust 1.80.0

### Operating System version

Linux (Default)

### Relevant log output

```shell
[parker@parker-framework rust]$ cargo build --release
    Updating crates.io index
     Locking 7 packages to latest compatible versions
      Adding bit-set v0.2.0 (latest: v0.8.0)
  Downloaded bit-vec v0.8.0
  Downloaded libusb-sys v0.2.3
  Downloaded bit-set v0.2.0
error: failed to parse manifest at `/home/parker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bit-set-0.2.0/Cargo.toml`

Caused by:
  dependency (bit-vec) specified without providing a local path, Git repository, version, or workspace dependency to use
```
```

**Comment by parkerlreed** [comment]
rusb seems to be the replacement

**Comment by raleighlittles** [comment]
Thanks for the heads up. I switched to `rusb` in the latest commit: https://github.com/raleighlittles/PS5-Camera-Firmware-Loader/commit/8a15817672ee4a50537d37b31e91104bf333d8b0
