### ISSUE TITLE
Completely fails to upload firmware on new computer

### ISSUE THREAD

**Issue by parkerlreed** [raleighlittles/PS5-Camera-Firmware-Loader#12]
### Provide a brief description of the issue

On a Framework 16, the firmware is never uploading at all. Before it would show the -4 "no device" error on the other machine while still uploading successfully but now it never drops out of bootloader mode.

Getting error -9 which is LIBUSB_ERROR_PIPE 

libusb 1.0.27-1

### Operating System version

Linux (Default)

### Which camera model was this for?

PlayStation 5

### Relevant log output

```shell
[parker@parker-framework cpp]$ ./ps5_camera_firmware_loader 21.01-03.20.00.04-00.00.00.bin 
ERROR: libusb reported error during control transfer, error# = -9
```

```
[ 2721.059760] usb 2-2.3: new SuperSpeed USB device number 9 using xhci_hcd
[ 2721.081259] usb 2-2.3: New USB device found, idVendor=05a9, idProduct=0580, bcdDevice= 1.00
[ 2721.081269] usb 2-2.3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 2721.081272] usb 2-2.3: Product: USB Boot 
[ 2721.081274] usb 2-2.3: Manufacturer: OmniVision Technologies, Inc.
```

**Comment by parkerlreed** [comment]
Seeing this on the other machine now as well... With the old compiled rust and firmware that worked before. Now I'm not sure what the heck is going on if it's not some weird libusb/kernel updates.

**Comment by parkerlreed** [comment]
Just compiled the rusb update and still seeing the pipe error.

Tried all my different USB ports, not going through a hub or anything weird.

```
[parker@parker-framework rust]$ sudo ./target/release/ps5_camera_firmware_loader ../cpp/21.01-03.20.00.04-00.00.00.bin 
thread 'main' panicked at src/main.rs:95:14:
called `Result::unwrap()` on an `Err` value: Pipe
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by parkerlreed** [comment]
Realized my stupid mistake. I `curl -L`'d the firmware GitHub page and now the raw binary... Of course it fails feeding it HTML... LOL. Working now. Sorry for that.

**Comment by raleighlittles** [comment]
@parkerlreed  Hah, no worries, it happens - everyone makes this mistake once. This does bring up a great point in that I should add some kind of validation code to check that the firmware file is valid before trying to program it.
