### ISSUE TITLE
[Bug] Can't use camera with PS5 anymore after installing UVC firmware

### ISSUE THREAD

**Issue by Ma110w** [raleighlittles/PS5-Camera-Firmware-Loader#9]
### Provide a brief description of the issue

I didnt think this thru and now i cant use the camera on my ps5, is there anyway to restore the original firmware or am i fucked?

### Operating System version

Linux (Default)

### Which camera model was this for?

PlayStation 5

**Comment by raleighlittles** [comment]
@Ma110w If you look at the documentation I said the firmware gets reset once you power cycle the device. https://github.com/raleighlittles/PS5-Camera-Firmware-Loader?tab=readme-ov-file#success--heavy_check_mark

Is that behavior _not_ happening to you? As in, when you're power cycling the camera is it still using the UVC firmware you flashed?

**Comment by Ma110w** [comment]
yeah, i have to load the uvc program still, but i power cycle the camera, and it refuses to work on the ps5

**Comment by raleighlittles** [comment]
Huh that's weird. I just tested my PS5 camera right now and it worked (screenshot from OBS)

![Screenshot_obs_2024-04-07-11-36-07](https://github.com/raleighlittles/PS5-Camera-Firmware-Loader/assets/2137201/6b411ea6-938a-417a-bf34-94be8b39e051)

Can you try restarting your PS5? As in, fully restart it, not just go into rest mode, and then plug in your camera.

Also check what PS5 firmware version you have. I have `24.02-09.00.00.45-00.00.00.0.1`


![Screenshot_obs_2024-04-07-11-39-23](https://github.com/raleighlittles/PS5-Camera-Firmware-Loader/assets/2137201/68e85747-007e-40a0-b52d-a2001de820da)


@Ma110w

**Comment by Ma110w** [comment]
Did that, and it didnt work im on `24.02-09.00.00.45-00.00.00.0.1`, the same as you

**Comment by raleighlittles** [comment]
So you first unplugged your PS5 camera. Then restarted your PS5. Then re-inserted your camera, and went to the "Adjust HD camera" section, and it said you didn't have a camera connected?

What do you see in the dmesg log when you connect your PS5 camera to your PC? @Ma110w

**Comment by Ma110w** [comment]
so, i did that, and also im on windows, not linux, my mistake, shoulda said that earlier, but with `USB Device Tree Viewer` from [HackInside](https://github.com/Hackinside/Playstation-camera-drivers) i get this [Output.txt](https://github.com/raleighlittles/PS5-Camera-Firmware-Loader/files/14898950/Output.txt)

**Comment by raleighlittles** [comment]
@Ma110w I'm so sorry, I'm not familiar with Windows, and in the log you sent I don't see any obvious error messages. I can't reproduce this issue at all. I wish I could help but I truly can't.

The only thing I could do for you at this point is offer to swap cameras with you, you would ship me yours and I could ship you mine as a replacement -- this would allow me to debug and test your unit specifically to try to see what the problem is.

**Comment by Ma110w** [comment]
i wouldn't mind that, we should probably move this to disco or something, ```jackhoffmen.``` is my disco
